"""empty message

Revision ID: 8a21ae799e64
Revises: 
Create Date: 2023-10-21 14:05:43.439303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a21ae799e64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('s3_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'IN_PROGRESS', 'DONE', name='batchstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_id'), 'batch', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_id'), table_name='batch')
    op.drop_table('batch')
    # ### end Alembic commands ###
