AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation for Localstack
Resources:
  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SqsQueue

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: fastapi-async-celery
